vim.g.mapleader = " "

require("plugins/nvim_web_devicons")
require("plugins/telescope")
require("plugins/treesitter")
require("plugins/nvim_treesitter_context")
require("plugins/gitsigns")
require("plugins/satellite")
require("plugins/hlsearch")
require("plugins/meow_yarn")
require("plugins/mason")
require("plugins/nvim_lspconfig")
require("plugins/lua_ls")
require("plugins/mason_lspconfig")
require("plugins/theme_hub")
require("netrw_session")

require("options")
require("tree")
require("statusline")
require("autocommands")
require("diagnostics")
require("formatting")
require("keymaps")
require("lsp")
